# Generated by Django 5.1.7 on 2025-04-04 15:13

from django.db import migrations
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password

def create_initial_admin(apps, schema_editor):
    # Create superuser
    if not User.objects.filter(username='admin1').exists():
        User.objects.create(
            username='admin1',
            password=make_password('admin1'),
            is_staff=True,
            is_superuser=True,
            email='admin1@example.com',
            first_name='Admin',
            last_name='User'
        )

def reverse_initial_admin(apps, schema_editor):
    # Delete superuser
    User.objects.filter(username='admin1').delete()

class Migration(migrations.Migration):
    dependencies = [
        ('register', '0002_create_initial_admin'),
    ]

    operations = [
        migrations.RunPython(create_initial_admin, reverse_initial_admin),
    ]
