# Generated by Django 5.1.7 on 2025-03-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="converted_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
